### ISSUE TITLE
Cluster annotation with no label text

### ISSUE THREAD

**Issue by ctaskin** [ashare80/TSClusterMapView#12]
@ashare80 When I was testing the latest version I see cluster annotations with no text several times. They were at close zoom levels. Did you see anything like that?
I could not recreate it, I will let you know if find out how to do it.
Thanks

**Comment by AdamShare** [comment]
@bigtigercahit  Yeah I need to revert a change that I thought might help #8 but didn't and causes this

**Comment by AdamShare** [comment]
@bigtigercahit  should be back to normal now with latest push

**Comment by ctaskin** [comment]
@ashare80  I will check that, thanks

**Comment by ctaskin** [comment]
@ashare80 I could not recreate it with a quick test, it looks fine. I will let you know if it happens again.
Thanks
