### ISSUE TITLE
Exchanging annotations location inside a cluster

### ISSUE THREAD

**Issue by zfrankz** [ashare80/TSClusterMapView#18]
Hello, after the update, I realised that annotations inside cluster are exchanging location. I attach some screenshots. The price I show is assigned as a property in the annotation (my annotation is a MKPlacemark subclass and that info is inside the AddressDictionary property).

LINKS TO THE SCREENSHOTS:
1. Get closer to a cluster of 3
   https://www.dropbox.com/s/c3qb5uxp0qzcwsx/changing_1.png?dl=0
2. Zoom out. One of my annotations disappear!
   https://www.dropbox.com/s/4zrtafzut1znddg/changing_2.png?dl=0
3. Zoom out (very far away). Zoom in. Now the cluster of 3 is back
   https://www.dropbox.com/s/jqrzk8g8jlgvxqe/changing_3.png?dl=0
4. Select the cluster, it zooms in and separate. Now the annotation in the left says 31 instead 57.1...
   https://www.dropbox.com/s/9mg4pgxzcrurbvj/changing_4.png?dl=0
5. Zoom out to get a cluster of 3 and then click again in the cluster. Now the annotation in the left says neg (negotiable)
   https://www.dropbox.com/s/9stkbjm3w21eg7v/changing_5.png?dl=0
6. Click in the cluster of 2 from the screenshot number 5, neg is now here!!
   https://www.dropbox.com/s/6xl6vrwmmu8i30x/changing_6.png?dl=0

**Comment by AdamShare** [comment]
@zfrankz  Maybe this latest update helps

**Comment by zfrankz** [comment]
I tried the latest update and fixed some issues in my code and looks like it is solved! thanks!!
