### ISSUE TITLE
Annotations are not visible if removed and added back again

### ISSUE THREAD

**Issue by uwinkler** [ashare80/TSClusterMapView#19]
Cluster annotations and normal annotations are not visible if one removes all annotations and than adds them back again to the MapView.

You can reproduce this behaviour using the TSCClusterMapViewDemo app

Step 1: press +All to add all public bathrooms. The cluster annotation will appear
Step 2: press -All to remove all annotations.
Step 3: press +All again. No cluster annotation will be visible. You have to scroll or zoom the map to force the annotations to appear

**Comment by AdamShare** [comment]
@uwinkler I think this is fixed in latest version. Let me know if not.

**Comment by uwinkler** [comment]
Cheers. I will have a look. By the way; your clustering view is one of the best. Great stuff :+1:
