### ISSUE TITLE
Drag spontaneously cancelled after moving a short distance

### ISSUE THREAD

**Issue by jpmhouston** [ashare80/TSClusterMapView#21]
In one mode of my mapview, its setup with a single draggable annotation with a custom view. After the drag starts and the annotation view has moved a few pixels (like 5-10), something is causing the mapview to set its drag state to `MKAnnotationViewDragStateEnding`. Also, the touch that was dragging the annotation starts scrolling the map instead. I change my mapview from a `TSClusterMapView` subclass to a plain `MKMapView` and this no longer happens.

The stack trace at the time seems only shows execution of the mapview's gesture recognizers. It looks like at this point the touch has already been taken over by the pan gesture recognizer for scrolling, and that this itself is causing the drag to end.

```
  * frame #0: 0x000000010750b6f6 Wundrit`-[PendingQuestionAnnotationView setDragState:animated:](self=0x00007ffcb9950620, _cmd=0x0000000116f54852, newDragState=MKAnnotationViewDragStateEnding, animated=false) + 342 at MainMapViewController.m:1485
    frame #1: 0x000000010a60cb81 MapKit`-[MKAnnotationContainerView _dropDraggingAnnotationViewAnimated:] + 280
    frame #2: 0x000000010a55cb95 MapKit`-[MKMapView _dropDraggingAnnotationView:] + 90
    frame #3: 0x000000010a55e10a MapKit`-[MKMapView _willChangeRegionAnimated:] + 87
    frame #4: 0x00000001169c2b29 VectorKit`-[VKMapCameraController startPanningAtPoint:panAtStartPoint:] + 89
    frame #5: 0x000000010a59ac21 MapKit`-[MKMapGestureController handlePan:] + 384
    frame #6: 0x000000010ab4c656 UIKit`_UIGestureRecognizerSendActions + 262
    frame #7: 0x000000010ab4b2f9 UIKit`-[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 532
```

So what could be causing the scrolling recognizer to be taking over the touch that started out belonging to the annotation drag?

I was thinking the `UIPanGestureRecognizer` that's setup in `initHelpers` was somehow to blame (what is the point of that anyway?), but I commented out the creation of that recognizer and the problem is still happening.

Any ideas for what this could be or how to debug this?

**Comment by jpmhouston** [comment]
Looks like my problem was caused by this:

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
}
```

I've removed it and everything to do with the added pan gesture recognizer and dragging works fine.

**Comment by AdamShare** [comment]
@jpmhouston Yes sorry that was carry over from the project which spawned this library.  I will make that piece optional/removed in the next update as it could result in undesirable effects as you have found.
