### ISSUE TITLE
Cluster Annotations is not visible.

### ISSUE THREAD

**Issue by jian1989** [ashare80/TSClusterMapView#25]
I have added new viewcontroller with TSClusterMapview. 
When I will open this viewcontroller at first, it's working as well. But If I will reopen viewcontroller again (without turn off app), any cluster is not showing.

I have tested it in example project also. It's same issue. If you will add new viewcontroller with TSClusterMapview and show via storyboard or code(self.navigationController pushviewcontroller: YES). You can see issue as well.
How can I fix this issue? Please help me.
Thanks.

**Comment by AdamShare** [comment]
@jian1989 What do you mean by "reopen viewcontroller again"?  Popping the nav then pushing again? Closing the app then reopening?

**Comment by AdamShare** [comment]
@jian1989 Try latest version should be fixed
