### ISSUE TITLE
How to select a clustered annotation programmatically?

### ISSUE THREAD

**Issue by yorgosg** [ashare80/TSClusterMapView#32]
Hi, 

I would like to select a clustered annotation programmatically to simulate the user pressing the annotation pin, in order for the map to zoom in to show the annotation's children.

I have tried calling selectAnnotation on the annotation I want to simulate the action in the didFinishBuildingClusterTreeForMapPoints method, with no luck so far. So, what I do is:

id <MKAnnotation> annotation = [mapView.visibleClusterAnnotations objectAtIndex:0];
[(TSClusterMapView *)mapView selectAnnotation:annotation animated:YES];

Nothing happens when doing this. I tried executing this code with a delay too.

Anyone knows how I would go about doing this? It seemed pretty simple at first.

Any help is appreciated. Cheers!

**Comment by AdamShare** [comment]
Hey @yorgosg You may be able to simulate this action by calling the mapView method for showing a MKMapRect and passing in the mapRect from the rootMapCluster property available on the mapView after the finished delegate.

**Comment by yorgosg** [comment]
Thanks a million Adam, that fixed it!

**Comment by mhmtcakir** [comment]
hi, i would like to zoom, expand and select a split cluster annotation programatically.  @yorgosg 

i m using mapView.showAnnotations method below to show selected annotation.

 _let selectedAnnotation  = annotationArray[Int(currentIndex)] as! ADClusterAnnotation
 var zoomArray:[MKAnnotation] = []
zoomArray.append(selectedAnnotation)
mapView.showAnnotations(zoomArray, animated: true)_

when i use these codes, mapView zoom to given annotation coordinate on map. SelectedAnnotation is member of a splitCluster. I cannot expand splitCluster and select annotation programatically.

Any help would be much appreciated!

**Comment by mhmtcakir** [comment]
i need help! @ashare80 @yorgosg

**Comment by yorgosg** [comment]
Look at lines 841-865 of TSClusterMapView.m, something similar is done there. First finding zoomTo and then setting the region of the map.
