### ISSUE TITLE
Cluster use 200% of cpu

### ISSUE THREAD

**Issue by jmrborges05** [ashare80/TSClusterMapView#36]
when i open tsclustermapview and touch on cluster to expand,  the cpu usage is 200% whose crash the app . i use tsclustermapview version 2.3.1 .

**Comment by CavalcanteLeo** [comment]
+1

same here

![captura de tela 2016-05-04 as 13 09 05](https://cloud.githubusercontent.com/assets/1735944/15020724/aa14506c-11f9-11e6-9966-feecf288d079.png)

https://github.com/ashare80/TSClusterMapView/blob/master/Pod/Classes/TSClusterOperation.m#L463

35k loops in this while

**Comment by CavalcanteLeo** [comment]
![captura de tela 2016-05-04 as 14 04 22](https://cloud.githubusercontent.com/assets/1735944/15022248/203ce540-1201-11e6-8f90-20be244633fe.png)

In another test, it did a little less loop, but still high

**Comment by AdamShare** [comment]
Cool I'll change that up on the next update.

**Comment by AdamShare** [comment]
@cavalcanteleo see if the latest version fixes

**Comment by CavalcanteLeo** [comment]
tkssss, i'll see it

**Comment by CavalcanteLeo** [comment]
there are many improvements on thsi commit https://github.com/ashare80/TSClusterMapView/pull/40/commits/b52f965430cc7d505e257b7e76913cc07bcaab8c

**Comment by jmrborges05** [comment]
thanks for fix :)
