### ISSUE TITLE
Zooming in and out shifts cluster annonations

### ISSUE THREAD

**Issue by ctaskin** [ashare80/TSClusterMapView#8]
Hi @ashare80,
I noticed another issue and I will provide some screenshots from your sample app tomorrow.

The clustered annotations are moving left when zooming in (displaying regular annotations) and zooming out. If you do it several times you can see the clustered annotations' position are moving left and a little bit down.

Thanks
Cahit

**Comment by AdamShare** [comment]
@bigtigercahit This is happening with the sample app or your own implementation?

**Comment by ctaskin** [comment]
Both

**Comment by ctaskin** [comment]
@ashare80 Here are some screenshots for the issue. Check the position of "2" cluster in the middle at SS1 and SS2. SS3 is the distributed version, regular annotations are not moving. It happens when zooming in to regular annotations and zooming out. They are mostly moving towards left with my POIs

https://dl.dropboxusercontent.com/u/2687801/Cluster/SS1.png
https://dl.dropboxusercontent.com/u/2687801/Cluster/SS2.png
https://dl.dropboxusercontent.com/u/2687801/Cluster/SS3.png

**Comment by AdamShare** [comment]
@bigtigercahit I need some help recreating the problem consistently.  I have seen this previously in developing the library but I thought it was fixed.

Anything in particular I should be doing to see this effect? What device are you testing on?

**Comment by ctaskin** [comment]
@ashare80 I observe the issue consistently when I distribute and regroup annotations with the same coordinate. I am not sure but I think higher numbers of annotation in the group increases the distance it moves.
I do not observe it for annotations with different coordinates. I can repeat it with iPhone6 iOS8  and Simulator.

I suggest you to add 10 annotations at the same coordinate, distribute the cluster at the final zoom level and zoom out, you will see the movement when you repeat this action.

Let me know if you need anything more or a video.

**Comment by AdamShare** [comment]
@bigtigercahit Ah ok that helps I'll check into that. If it is what I think it is, it will be an easy fix.  Thanks!

**Comment by AdamShare** [comment]
@bigtigercahit Pushed code to fix issue. Let me know if it is fixed for you as well

**Comment by ctaskin** [comment]
@ashare80 Yes it is fixed for me as well...
Thanks
