### ISSUE TITLE
Annotation with 0,0 center offset animation problem 

### ISSUE THREAD

**Issue by ctaskin** [ashare80/TSClusterMapView#9]
Hi @ashare80,
I used "self.centerOffset = CGPointMake(0,0);" for a different annotation image in "ClusteredAnnotationView", but animation problems occurred when playing with the map. 
Modifying "TSClusterAnnotationView" with code below solved the problem.
FYI

//    if (!CGPointEqualToPoint(self.centerOffset, annotationView.centerOffset)) {
//        self.centerOffset = annotationView.centerOffset;
//    }
    self.centerOffset = annotationView.centerOffset;

**Comment by AdamShare** [comment]
is this related to #8 or is that still a problem as well?

**Comment by ctaskin** [comment]
Nope, it did not solve the #8 issue

**Comment by AdamShare** [comment]
OK thanks!
